<?php
/**
 * Widget Manifest for Marquee Addons
 *
 * This file acts as a single source of truth for all widget configurations,
 * containing both display-related information and technical registration details.
 */

if (!defined('ABSPATH')) exit;

return [
    'deensimc-image-marquee' => [
        'title'  => __('Image Marquee', 'marquee-addons-for-elementor'),
        'icon'   => 'deensimc-image-marquee-icon',
        'is_pro' => false,
        'demo'   => 'https://marqueeaddons.com/image-marquee/',
        'cat'    => 'general',
        'pro_url' => '',
        'traits' => [
            '/includes/widgets/traits/image-marquee/content-image.php',
            '/includes/widgets/traits/image-marquee/style-image-controls.php',
            '/includes/widgets/traits/image-marquee/style-caption-controls.php',
        ],
        'file' => '/includes/widgets/class-deensimc-image-marquee.php',
        'class' => '\Deensimc_Image_Marquee',
    ],
    'deensimc-text-marquee' => [
        'title'  => __('Text Marquee', 'marquee-addons-for-elementor'),
        'icon'   => 'deensimc-text-marquee-icon',
        'is_pro' => false,
        'demo'   => 'https://marqueeaddons.com/text-marquee/',
        'cat'    => 'general',
        'pro_url' => '',
        'traits' => [
            '/includes/widgets/traits/text-marquee/content-text-repeater.php',
            '/includes/widgets/traits/text-marquee/style-text-contents.php',
        ],
        'file' => '/includes/widgets/class-deensimc-text-marquee.php',
        'class' => '\Deensimc_Text_Marquee',
    ],
    'deensimc-testimonial-marquee' => [
        'title'  => __('Testimonial Marquee', 'marquee-addons-for-elementor'),
        'icon'   => 'deensimc-testimonial-marquee-icon',
        'is_pro' => false,
        'demo'   => 'https://marqueeaddons.com/testimonial-marquee/',
        'cat'    => 'general',
        'pro_url' => '',
        'traits' => [
            '/includes/widgets/traits/testimonial-marquee/helper-methods.php',
            '/includes/widgets/traits/testimonial-marquee/content-repeater.php',
            '/includes/widgets/traits/testimonial-marquee/content-text-unfold.php',
            '/includes/widgets/traits/testimonial-marquee/style-contents-box.php',
            '/includes/widgets/traits/testimonial-marquee/style-contents.php',
            '/includes/widgets/traits/testimonial-marquee/style-image.php',
            '/includes/widgets/traits/testimonial-marquee/style-name-title.php',
            '/includes/widgets/traits/testimonial-marquee/style-review.php',
        ],
        'file' => '/includes/widgets/class-deensimc-testimonial-marquee.php',
        'class' => '\Deensimc_Testimonial_Marquee',
    ],
    'deensimc-video-marquee' => [
        'title'  => __('Video Marquee', 'marquee-addons-for-elementor'),
        'icon'   => 'deensimc-video-marquee-icon',
        'is_pro' => false,
        'demo'   => 'https://marqueeaddons.com/video-marquee/',
        'cat'    => 'general',
        'pro_url' => '',
        'traits' => [
            '/includes/widgets/traits/video-marquee/helper-methods.php',
            '/includes/widgets/traits/video-marquee/content-url-fields.php',
            '/includes/widgets/traits/video-marquee/content-video-options.php',
            '/includes/widgets/traits/video-marquee/content-youtube-vimeo.php',
            '/includes/widgets/traits/video-marquee/content-hosted.php',
            '/includes/widgets/traits/video-marquee/content-image-overlay.php',
            '/includes/widgets/traits/video-marquee/style-contents.php',
            '/includes/widgets/traits/video-marquee/style-play-icon.php',
        ],
        'file' => '/includes/widgets/class-deensimc-video-marquee.php',
        'class' => '\Deensimc_Video_Marquee',
    ],
    'deensimc-stacked-slider' => [
        'title'  => __('Stacked Slider', 'marquee-addons-for-elementor'),
        'icon'   => 'deensimc-stacked-slider-icon',
        'is_pro' => false,
        'demo'   => 'https://marqueeaddons.com/stacked-slider/',
        'cat'    => 'general',
        'pro_url' => '',
        'traits' => [
            '/includes/widgets/traits/stacked-slider/content-advance.php',
            '/includes/widgets/traits/stacked-slider/content-primary.php',
            '/includes/widgets/traits/stacked-slider/style-box.php',
            '/includes/widgets/traits/stacked-slider/content-parts/style-title-controls.php',
            '/includes/widgets/traits/stacked-slider/content-parts/style-description-controls.php',
            '/includes/widgets/traits/stacked-slider/content-parts/style-color-controls.php',
            '/includes/widgets/traits/stacked-slider/content-parts/style-button-controls.php',
            '/includes/widgets/traits/stacked-slider/style-contents.php',
            '/includes/widgets/traits/stacked-slider/style-image.php',
            '/includes/widgets/traits/stacked-slider/style-dots.php',
        ],
        'file' => '/includes/widgets/class-deensimc-stacked-slider.php',
        'class' => '\Deensimc_Stacked_Slider',
    ],
    'deensimc-image-accordion' => [
        'title'  => __('Image Accordion', 'marquee-addons-for-elementor'),
        'icon'   => 'deensimc-image-accordion-icon',
        'is_pro' => false,
        'demo'   => 'https://marqueeaddons.com/marquee-demos/image-accordion/',
        'cat'    => 'general',
        'pro_url' => '',
        'traits' => [
            '/includes/widgets/traits/image-accordion/content.php',
            '/includes/widgets/traits/image-accordion/style.php',
        ],
        'file' => '/includes/widgets/class-deensimc-image-accordion.php',
        'class' => '\Deensimc_Image_Accordion',
    ],
    'deensimc-news-ticker' => [
        'title'  => __('News Ticker', 'marquee-addons-for-elementor'),
        'icon'   => 'deensimc-news-ticker-icon',
        'is_pro' => false,
        'demo'   => 'https://marqueeaddons.com/news-ticker/',
        'cat'    => 'general',
        'pro_url' => '',
        'traits' => [
            '/includes/widgets/traits/news-ticker/news-ticker-layout-control.php',
            '/includes/widgets/traits/news-ticker/style-section-control.php',
            '/includes/widgets/traits/news-ticker/news-ticker-query-control.php',
        ],
        'file' => '/includes/widgets/class-deensimc-news-ticker.php',
        'class' => '\Deensimc_News_Ticker',
    ],
    'deensimc-animated-word-roller' => [
        'title'  => __('Animated Word Roller', 'marquee-addons-for-elementor'),
        'icon'   => 'deensimc-animated-word-roller-icon',
        'is_pro' => false,
        'demo'   => 'https://marqueeaddons.com/marquee-demos/animated-word-roller/',
        'cat'    => 'general',
        'pro_url' => '',
        'traits' => [
            '/includes/widgets/traits/animated-word-roller/content-additional-options.php',
            '/includes/widgets/traits/animated-word-roller/content-text-repeater.php',
            '/includes/widgets/traits/animated-word-roller/style-contents.php',
        ],
        'file' => '/includes/widgets/class-deensimc-animated-word-roller.php',
        'class' => '\Deensimc_Animated_Word_Roller',
    ],
    'deensimc-animated-heading' => [
        'title'  => __('Animated Heading', 'marquee-addons-for-elementor'),
        'icon'   => 'deensimc-animated-heading-icon',
        'is_pro' => false,
        'demo'   => 'https://marqueeaddons.com/animated-heading/',
        'cat'    => 'general',
        'pro_url' => '',
        'traits' => [
            '/includes/widgets/traits/animated-heading/trait-animated-text-effect-controls.php',
            '/includes/widgets/traits/animated-heading/trait-animation-controls.php',
            '/includes/widgets/traits/animated-heading/trait-text-styles-controls.php',
            '/includes/widgets/traits/animated-heading/trait-title-controls.php',
        ],
        'file' => '/includes/widgets/class-deensimc-animated-heading.php',
        'class' => '\Deensimc_Animated_Heading_Widget',
    ],
    'deensimc-button-marquee' => [
        'title'  => __('Button Marquee', 'marquee-addons-for-elementor'),
        'icon'   => 'deensimc-button-marquee-icon',
        'is_pro' => false,
        'demo'   => 'https://marqueeaddons.com/button-marquee/',
        'cat'    => 'general',
        'pro_url' => '',
        'traits' => [
            '/includes/widgets/traits/button-marquee/trait-button-controls.php',
            '/includes/widgets/traits/button-marquee/trait-button-style-controls.php',
            '/includes/widgets/traits/button-marquee/trait-button-marquee-controls.php',
            '/includes/widgets/traits/button-marquee/trait-button-helper-methods.php',
        ],
        'file' => '/includes/widgets/class-deensimc-button-marquee.php',
        'class' => '\Deensimc_Button_marquee',
    ],
    'deensimc-search-box' => [
        'title'  => __('Search Box', 'marquee-addons-for-elementor'),
        'icon'   => 'deensimc-search-icon',
        'is_pro' => false,
        'demo'   => '#',
        'cat'    => 'general',
        'pro_url' => '',
        'traits' => [
            '/includes/widgets/traits/search/clear-styles-controls.php',
            '/includes/widgets/traits/search/query-content-controls.php',
            '/includes/widgets/traits/search/search-content-controls.php',
            '/includes/widgets/traits/search/search-field-styles.php',
            '/includes/widgets/traits/search/style-triggerer-controls.php',
            '/includes/widgets/traits/search/submit-styles-controls.php',
        ],
        'file' => '/includes/widgets/class-deensimc-search.php',
        'class' => '\Deensimc_Search_Widget',
    ],

    // PRO Widgets will be merged here from the 'WidgetsList' trait
    // Extensions are also widgets, so they belong here too.
    'deensimcpro-container-background' => [
        'cat'    => 'extensions',
        'title'  => __('Container Background', 'marquee-addons-for-elementor'),
        'icon'   => 'dashicons dashicons-admin-appearance',
        'is_pro' => true,
        'demo'   => 'https://marqueeaddons.com/',
        'pro_url' => 'https://marqueeaddons.com/pricing/',
    ],
    'deensimcpro-heading-effect' => [
        'cat'    => 'extensions',
        'title'  => __('Heading Effect', 'marquee-addons-for-elementor'),
        'icon'   => 'dashicons dashicons-editor-textcolor',
        'is_pro' => true,
        'demo'   => 'https://marqueeaddons.com/',
        'pro_url' => 'https://marqueeaddons.com/pricing/',
    ],
    'deensimcpro-image-rotation' => [
        'cat'    => 'extensions',
        'title'  => __('Image Rotation', 'marquee-addons-for-elementor'),
        'icon'   => 'dashicons dashicons-format-image',
        'is_pro' => true,
        'demo'   => 'https://marqueeaddons.com/',
        'pro_url' => 'https://marqueeaddons.com/pricing/',
    ],
];
