<?php

namespace Deensimc_Marquee\Misc;


class Marquee_Addons_Pro_Widgets_Placeholder
{

    public static function get_pro_widget_map()
    {
        return [
            'advanced-heading'          => [
                'cat'    => 'general',
                'title'  => __('Advanced Heading', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-advanced-heading',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-advanced-heading-widget-demo/',
            ],
            'list-group'                => [
                'cat'    => 'general',
                'title'  => __('List Group', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-list-group',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-list-group-widget-demo/',
            ],
            'metro-grid' => [
                'cat' => 'general',
                'title' => __('Metro Grid', 'happy-addons-pro'),
                'icon' => 'hm hm-metro-grid-text-outline',
                'is_pro' => true,
                'demo'      => 'https://happyaddons.com/docs/happy-addons-for-elementor-pro/happy-effects-pro/metro-grid/',
            ],
            'loop-tab' => [
                'cat' => 'creative',
                'title' => __('Loop Tab', 'happy-addons-pro'),
                'icon' => 'hm hm-edd-my-account-tab',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/loop-tab/',
            ],
            'hover-box'                 => [
                'cat'    => 'creative',
                'title'  => __('Hover Box', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-finger-point',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-image-hover-box-widget-demo/',
            ],
            'countdown'                 => [
                'cat'    => 'general',
                'title'  => __('Countdown', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-refresh-time',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-countdown-widget-demo/',
            ],
            'team-carousel'             => [
                'cat'    => 'slider-&-carousel',
                'title'  => __('Team Carousel', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-team-carousel',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-team-carousel-widget-demo/',
            ],
            'logo-carousel'             => [
                'cat'    => 'slider-&-carousel',
                'title'  => __('Logo Carousel', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-logo-carousel',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-logo-carousel-widget-demo/',
            ],
            'source-code'               => [
                'cat'    => 'general',
                'title'  => __('Source Code', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-code-browser',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-source-code-widget-demo/',
            ],
            'feature-list'              => [
                'cat'    => 'general',
                'title'  => __('Feature List', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-list-2',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-feature-list-widget-demo/',
            ],
            'testimonial-carousel'      => [
                'cat'    => 'slider-&-carousel',
                'title'  => __('Testimonial Carousel', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-testimonial-carousel',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-testimonial-carousel-widget-demo/',
            ],
            'advanced-tabs'             => [
                'cat'    => 'general',
                'title'  => __('Advanced Tabs', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-tab',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-advanced-tab-widget-demo/',
            ],
            'advanced-flip-box'         => [
                'cat'    => 'creative',
                'title'  => __('Advanced Flip Box', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-flip-card1',
                'is_pro' => true,
                'demo'      => '',
            ],
            'animated-text'             => [
                'cat'    => 'creative',
                'title'  => __('Animated Text', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-text-animation',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elemento-animated-text-widget-demo/',
            ],
            'timeline'                  => [
                'cat'    => 'general',
                'title'  => __('Timeline', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-timeline',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-timeline-widget-demo/',
            ],
            'instagram-feed'            => [
                'cat'    => 'social-media',
                'title'  => __('Instagram Feed', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-instagram',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-instagram-feed-widget-demo/',
            ],
            'scrolling-image'           => [
                'cat'    => 'creative',
                'title'  => __('Scrolling Image', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-scrolling-image',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-scrolling-image-widget-demo/',
            ],
            'advanced-pricing-table'    => [
                'cat'    => 'marketing',
                'title'  => __('Advanced Pricing Table', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-file-cabinet',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-pricing-table-widget-demo/',
            ],
            'business-hour'             => [
                'cat'    => 'general',
                'title'  => __('Business Hour', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-hand-watch',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-business-hour-widget-demo/',
            ],
            'accordion'                 => [
                'cat'    => 'general',
                'title'  => __('Advanced Accordion', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-accordion-vertical',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-advanced-accordion-widget-demo/',
            ],
            'toggle'                    => [
                'cat'    => 'general',
                'title'  => __('Advanced Toggle', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-accordion-vertical',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-advanced-toggle-widget-demo/',
            ],
            'promo-box'                 => [
                'cat'    => 'marketing',
                'title'  => __('Promo Box', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-promo',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-promo-box-widget-demo/',
            ],
            'hotspots'                  => [
                'cat'    => 'creative',
                'title'  => __('Hotspots', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-accordion-vertical',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-hot-spot-widgets-demo/',
            ],
            'price-menu'                => [
                'cat'    => 'marketing',
                'title'  => __('Price Menu', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-menu-price',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-price-menu-widget-demo/',
            ],
            'facebook-feed'             => [
                'cat'    => 'social-media',
                'title'  => __('Facebook Feed', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-facebook',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-facebook-feed-widget-demo/',
            ],
            'line-chart'                => [
                'cat'    => 'chart',
                'title'  => __('Line Chart', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-line-graph-pointed',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-line-chart-widget-demo/',
            ],
            'pie-chart'                 => [
                'cat'    => 'chart',
                'title'  => __('Pie & Doughnut Chart', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-graph-pie',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-pie-doughnut-chart-widget-demo/',
            ],
            'polar-chart'               => [
                'cat'    => 'chart',
                'title'  => __('Polar area Chart', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-graph-pie',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-polar-area-chart-widget-demo/',
            ],
            'radar-chart'               => [
                'cat'    => 'chart',
                'title'  => __('Radar Chart', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-graph-pie',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-radar-chart-widget-demo/',
            ],
            'post-tiles'                => [
                'cat'    => 'post',
                'title'  => __('Post Tiles', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-article',
                'is_pro' => true,
                'demo'      => '',
            ],
            'post-carousel'             => [
                'cat'    => 'post',
                'title'  => __('Post Carousel', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-graph-pie',
                'is_pro' => true,
                'demo'      => '',
            ],
            'smart-post-list'           => [
                'cat'    => 'post',
                'title'  => __('Smart Post List', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-post-list',
                'is_pro' => true,
                'demo'      => '',
            ],
            'breadcrumbs'               => [
                'cat'    => 'general',
                'title'  => __('Breadcrumbs', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-breadcrumbs',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-breadcrumb-widget-demo/',
            ],
            'twitter-carousel'          => [
                'cat'    => 'social-media',
                'title'  => __('X Feed Carousel', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-twitter',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-twitter-feed-carousel-widget-demo/',
            ],
            'author-list'               => [
                'cat'    => 'post',
                'title'  => __('Author List', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-user-male',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-author-list-widget-demo/',
            ],
            'post-grid-new'                 => [
                'cat'    => 'post',
                'title'  => __('Post Grid', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-post-grid',
                'is_pro' => true,
                'demo'      => '',
            ],
            'sticky-video'              => [
                'cat'    => 'general',
                'title'  => __('Sticky Video', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-sticky-video',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-sticky-video-widget-demo/',
            ],
            'product-carousel-new'          => [
                'cat'    => 'woocommerce',
                'title'  => __('Product Carousel', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-Product-Carousel',
                'is_pro' => true,
                'demo'      => '',
            ],
            'product-category-carousel-new' => [
                'cat'    => 'woocommerce',
                'title'  => __('Product Category Carousel', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-Category-Carousel',
                'is_pro' => true,
                'demo'      => '',
            ],
            'product-grid-new'              => [
                'cat'    => 'woocommerce',
                'title'  => __('Product Grid', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-Product-Grid',
                'is_pro' => true,
                'demo'      => '',
            ],
            'product-category-grid-new'     => [
                'cat'    => 'woocommerce',
                'title'  => __('Product Category Grid', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-Category-Carousel',
                'is_pro' => true,
                'demo'      => '',
            ],
            'single-product-new'            => [
                'cat'    => 'woocommerce',
                'title'  => __('Single Product', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-Category-Carousel',
                'is_pro' => true,
                'demo'      => '',
            ],
            'advanced-data-table'       => [
                'cat'    => 'general',
                'title'  => __('Advanced Data Table', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-data-table',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-advanced-datatable-widget-demo/',
            ],
            'modal-popup'               => [
                'cat'    => 'general',
                'title'  => __('Modal Popup', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-popup',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-modal-popup-widget-demo/',
            ],
            'multi-scroll' => [
                'title' => __('Multi Scroll', 'happy-addons-pro'),
                'icon' => 'hm hm-multi-page-scroll',
                'is_pro' => true,
                'demo'      => 'https://happyaddons.com/docs/happy-addons-for-elementor-pro/happy-effects-pro/multi-scroll/',
            ],
            'one-page-nav'              => [
                'cat'    => 'creative',
                'title'  => __('One Page Nav', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-dot-navigation',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-one-page-navigation-widget-demo/',
            ],
            'advanced-slider'           => [
                'cat'    => 'slider-&-carousel',
                'title'  => __('Advanced Slider', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-slider',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-advanced-slider-widget-demo/',
            ],
            'mini-cart'                 => [
                'cat'    => 'woocommerce',
                'title'  => __('Mini Cart', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-mini-cart',
                'is_pro' => true,
                'demo'      => '',
            ],
            'wc-cart'                   => [
                'cat'    => 'woocommerce',
                'title'  => __('WooCommerce Cart', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-cart',
                'is_pro' => true,
                'demo'      => '',
            ],
            'wc-checkout'               => [
                'cat'    => 'woocommerce',
                'title'  => __('WooCommerce Checkout', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-cart',
                'is_pro' => true,
                'demo'      => '',
            ],
            'image-scroller'            => [
                'cat'    => 'creative',
                'title'  => __('Single Image Scroll', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-image-scroll',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/single-image-scroll-widget-demo/',
            ],
            'nav-menu'                  => [
                'cat'    => 'general',
                'title'  => __('Happy Menu', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-mega-menu',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/happymenu/',
            ],
            'off-canvas'                => [
                'cat'    => 'creative',
                'title'  => __('Off Canvas', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-offcanvas-menu',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-off-canvas-content-demo/',
            ],
            'unfold'                    => [
                'cat'    => 'general',
                'title'  => __('Unfold', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-unfold-paper',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-unfold-widget-demo/',
            ],
            'edd-product-grid'          => [
                'cat'    => 'Easy Digital Downloads',
                'title'  => __('EDD Product Grid', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-product-grid',
                'is_pro' => true,
                'demo'      => '',
            ],
            'edd-product-carousel'      => [
                'cat'    => 'Easy Digital Downloads',
                'title'  => __('EDD Product Carousel', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-Product-Carousel',
                'is_pro' => true,
                'demo'      => '',
            ],
            'edd-single-product'        => [
                'cat'    => 'Easy Digital Downloads',
                'title'  => __('EDD Single Product', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-Category-Carousel',
                'is_pro' => true,
                'demo'      => '',
            ],
            'edd-category-grid'         => [
                'cat'    => 'Easy Digital Downloads',
                'title'  => __('EDD Category Grid', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-Category-Carousel',
                'is_pro' => true,
                'demo'      => '',
            ],
            'edd-category-carousel'     => [
                'cat'    => 'Easy Digital Downloads',
                'title'  => __('EDD Category Carousel', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-Category-Carousel',
                'is_pro' => true,
                'demo'      => '',
            ],
            'edd-cart' => [
                'cat' => 'easy-digital-downloads',
                'title' => __('EDD Cart', 'marquee-addons-for-elementor'),
                'icon' => 'hm hm-cart',
                'is_pro' => true,
                'demo'      => '',
            ],
            'edd-checkout' => [
                'cat' => 'easy-digital-downloads',
                'title' => __('EDD Checkout', 'marquee-addons-for-elementor'),
                'icon' => 'hm hm-checkout-2',
                'is_pro' => true,
                'demo'      => '',
            ],
            'edd-login' => [
                'cat' => 'easy-digital-downloads',
                'title' => __('EDD Login', 'marquee-addons-for-elementor'),
                'icon' => 'hm hm-checkout-2',
                'is_pro' => true,
                'demo'      => '',
            ],
            'edd-register' => [
                'cat' => 'easy-digital-downloads',
                'title' => __('EDD Register', 'marquee-addons-for-elementor'),
                'icon' => 'hm hm-user-plus',
                'is_pro' => true,
                'demo'      => '',
            ],
            'edd-purchase' => [
                'cat' => 'easy-digital-downloads',
                'title' => __('EDD Purchase', 'marquee-addons-for-elementor'),
                'icon' => 'hm hm-user-plus',
                'is_pro' => true,
                'demo'      => '',
            ],
            'edd-download' => [
                'cat' => 'easy-digital-downloads',
                'title' => __('EDD Download', 'marquee-addons-for-elementor'),
                'icon' => 'hm hm-Download-circle',
                'is_pro' => true,
                'demo'      => '',
            ],
            'google-map'                => [
                'cat'    => 'general',
                'title'  => __('Advanced Google Map', 'marquee-addons-for-elementor'),
                'icon'   => 'hm hm-map-marker',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-google-map-widget-demo/',
            ],
            'image-swap' => [
                'cat' => 'general',
                'title' => __('Image Swap', 'marquee-addons-for-elementor'),
                'icon' => 'hm hm-image-scroll',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-image-swap-widget-demo/',
            ],
            'shipping-bar' => [
                'cat' => 'woocommerce',
                'title' => __('Shipping Bar', 'marquee-addons-for-elementor'),
                'icon' => 'hm hm-shipping-address',
                'is_pro' => true,
                'demo'      => '',
            ],
            'remote-carousel' => [
                'cat' => 'slider-&-carousel',
                'title' => __('Remote Carousel', 'marquee-addons-for-elementor'),
                'icon' => 'hm hm-remote_carousel',
                'is_pro' => true,
                'demo'      => 'https://happyaddons.com/docs/happy-addons-for-elementor-pro/happy-effects-pro/remote-carousel/',
            ],
            'table-of-contents' => [
                'cat' => 'general',
                'title' => __('Table of Contents', 'marquee-addons-for-elementor'),
                'icon' => 'hm hm-list-2',
                'is_pro' => true,
                'demo'      => 'https://demo-x.happyaddons.com/elementor-table-of-content-widget-demo/',
            ],
            'creative-slider' => [
                'cat' => 'slider-&-carousel',
                'title' => __('Creative Slider', 'marquee-addons-for-elementor'),
                'icon' => 'hm hm-slider',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-creative-slider-widget-demo/',
            ],
            'title-tips' => [
                'cat' => 'general',
                'title' => __('Title Tips', 'happy-addons-pro'),
                'icon' => 'hm hm-title-tips-vector-path',
                'is_pro' => true,
                'demo'      => 'https://demo-x.happyaddons.com/title-tips-widget-demo/',
            ],
            'advanced-comparison-table'    => [
                'cat'       => 'creative',
                'title'     => __('Advanced Comparison Table', 'happy-addons-pro'),
                'icon'      => 'hm hm-link-box',
                'is_pro' => true,
                'demo'      => 'https://demo.happyaddons.com/elementor-advanced-comparison-table-widget-demo-mosaddek/',
            ],
        ];
    }

    public static function editor_enqueue()
    {
        $localize_data = [
            'placeholder_widgets' => [],
            'hasPro'                  => false,
            'i18n' => [
                'promotionDialogHeader'     => esc_html__('%s Widget', 'marquee-addons-for-elementor'),
                'promotionDialogMessage'    => esc_html__('Use %s widget with other exclusive pro widgets and 100% unique features to extend your toolbox and build sites faster and better.', 'marquee-addons-for-elementor'),
                'promotionDialogBtnTxt'    => esc_html__('Upgrade Now', 'marquee-addons-for-elementor'),
                'templatesEmptyTitle'       => esc_html__('No Templates Found', 'marquee-addons-for-elementor'),
                'templatesEmptyMessage'     => esc_html__('Try different category or sync for new templates.', 'marquee-addons-for-elementor'),
                'templatesNoResultsTitle'   => esc_html__('No Results Found', 'marquee-addons-for-elementor'),
                'templatesNoResultsMessage' => esc_html__('Please make sure your search is spelled correctly or try a different words.', 'marquee-addons-for-elementor'),
            ],
        ];

        $localize_data['placeholder_widgets'] = self::get_pro_widget_map();

        wp_localize_script(
            'deensimc-editor-script',
            'MarqueeAddonsEditor',
            $localize_data
        );
    }
}
