# Deploy to WP.org
name: Deploy to WordPress.org readme.txt and assets only

on:
  push:
    branches: [ trunk ]
    paths:
      - 'readme.txt'
      - '.wordpress-org/**'
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Assets Update
        id: assets
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: marquee-addons-for-elementor
          ASSETS_DIR: .wordpress-org
          IGNORE_OTHER_FILES: "true" 
